// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCopyrightAttribute("Copyright (C) Stompy Robot LTD 2019")]
[assembly: AssemblyCompanyAttribute("Stompy Robot LTD")]
[assembly: AssemblyVersionAttribute("1.4.1")]
[assembly: AssemblyInformationalVersionAttribute("1.4.1")]
[assembly: AssemblyFileVersionAttribute("1.4.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.4.1";
    }
}
